name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run tests
        run: |
          python -m pytest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t alokratan/devops-demo:1.0 .

      - name: Push Docker image
        run: |
          docker push alokratan/devops-demo:1.0

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            docker pull alokratan/devops-demo:1.0
            docker stop devops-demo || true
            docker rm devops-demo || true

            docker run -d \
              --restart unless-stopped \
              -p 8000:8000 \
              --name devops-demo \
              alokratan/devops-demo:1.0
